import type { Metadata } from 'next';
import './globals.css';

import LayoutWrapper from '../components/LayoutWrapper';
import Header from '../components/common/Header/Header';
import Footer from '../components/common/Footer/Footer';

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="ko">
      <body>
        <LayoutWrapper>{children}</LayoutWrapper>
      </body>
    </html>
  );
}
